### ISSUE TITLE
Structural variants in seqr

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#112]
Loading structural variants is one of the biggest _wants_ for our instance of Seqr.

I've jotted down a few rough points that have / will be needed to address to solve these. If you have related cards, please edit _this description_ to include tasks for those items. So hopefully, when this checklist is complete, we're able to say to collaborators we can generate and load structural variants.

## Background

The [SV loading pipeline](https://github.com/populationgenomics/hail-elasticsearch-pipelines/blob/main/sv_pipeline/genome/load_data.py) for seqr is fairly simple, it expects a single VCF file, that through some testing code contains structural variants for multiple samples, from multiple callers. 

We know that the Broad is using the `gatk-sv` pipeline, even though it's still fluctuating, it would be great to use that pipeline.

## Task list

- [ ] Investigate gatk-sv pipeline, and determine suitability
- [ ] Determine the bridge between Hail Batch and Cromwell (https://github.com/populationgenomics/analysis-runner/pull/274)
- [ ] Production-ization of GATK-SV (https://github.com/populationgenomics/production-pipelines/issues/6)
- [ ] SV Loading pipeline into Seqr
- [ ] Testing SV integration in Seqr

## About this card

This is a FEATURE card and exists on the [Seqr project board](https://github.com/orgs/populationgenomics/projects/9). It's an amalgamation of the individual tasks from individual teams required to completely ship this feature. Having this card here makes it easier to track high-level progress on an issue.

Tagging @lgruen, @vladsaveliev, @vivbak as the card is particularly relevant to you when it is created.

**Comment by rociorius** [comment]
This issue has been resolved for a while but remained open. Closing now.
