### ISSUE TITLE
Exomes in Seqr

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#113]
Loading SNVs and Indels for exomes in seqr is a high priority for our rare-disease collaborations using seqr.

## Background

We have a well established process for processing WGS data we get from collaborators. 

## Task list

- [ ] Discuss the implications of loading exomes into Seqr:
    - can WGS and exome data be loaded into the same project?
- [ ] Modify the metadata templates to include sample_type.
- [ ] Modify the sample-metadata database to support updated templates (https://github.com/populationgenomics/sample-metadata/issues/149)
- [ ] Modify the loading pipeline to accept samples from Exomes OR WGS.
    - More complex than this, what parameters need to change between WGS / Exomes.
    - How well does DRAGEN-GATK handle exomes?
    - How to sensibly split this without much code duplication?
- [ ] Modify our RD process to ensure if exomes / WGS are handled different through load, they're loaded correctly.

## About this card

This is a FEATURE card and exists on the [Seqr project board](https://github.com/orgs/populationgenomics/projects/9). It's an amalgamation of the individual tasks from individual teams required to completely ship this feature. Having this card here makes it easier to track high-level progress on an issue.

I've listed a few tasks that have / will be needed to address to solve this enhancement. If you have related cards, please edit _this description_ to include tasks for those items. So hopefully, when this checklist is complete, we're able to say to collaborators we can generate and load structural variants.

Tagging @lgruen, @vladsaveliev, @vivbak as the card is particularly relevant to you when it is created.

**Comment by rociorius** [comment]
This issue has been resolved for a while but remained open. Closing now.
