### ISSUE TITLE
Structural viewer in Seqr

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#114]
A structural viewer in seqr is possibly an area without much active development, and could be a valuable contribution to seqr for improved variant curation.

## Background

<TBA>

## Task list

- [ ] Initial investigation into what structural browsers already exist
- [ ] Developing a pilot / standalone structural browser for testing, that could be included in Seqr
- [ ] Include new structural viewer plugin in seqr.

## About this card

This is a FEATURE card and exists on the [Seqr project board](https://github.com/orgs/populationgenomics/projects/9). It's an amalgamation of the individual tasks from individual teams required to completely ship this feature. Having this card here makes it easier to track high-level progress on an issue.

I've listed a few tasks that have / will be needed to address to solve this enhancement. If you have related cards, please edit _this description_ to include tasks for those items. So hopefully, when this checklist is complete, we're able to say to collaborators we can generate and load structural variants.

Tagging @lgruen, @daniaki, @danielreti.
