### ISSUE TITLE
API access for Seqr

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#115]
API Access in seqr will be an important piece for our automated systems to interact with seqr. 

## Background

As we as the centre expand our usage of seqr, it's important to think about how the tasks we do scale, and where we can make important optimisations and automations.

Some use cases we're considering

- How to generate direct links into seqr functionality, only given the external family / participant IDs.
- How can the sample-metadata server give seqr updated metadata.

We know that 

## Task list

- [ ] Investigate the security implications of opening up parts of seqr. Does it affect the FEDRAMP certification.
- [ ] Implement a new authentication system, currently our instance of seqr uses OAuth2 with [CSRF protection](https://portswigger.net/web-security/csrf/tokens).
- [ ] Consider our use case and security implications, decide whether to:
    - [ ] Expose existing APIs
    - [ ] Create new APIs.
- [ ] Test the integration

## About this card

This is a FEATURE card and exists on the [Seqr project board](https://github.com/orgs/populationgenomics/projects/9). It's an amalgamation of the individual tasks from individual teams required to completely ship this feature. Having this card here makes it easier to track high-level progress on an issue.

I've listed a few tasks that have / will be needed to address to solve this enhancement. If you have related cards, please edit _this description_ to include tasks for those items. So hopefully, when this checklist is complete, we're able to say to collaborators we can generate and load structural variants.

Tagging @lgruen, @cassimons, @MattWellie, @violetbrina.
