### ISSUE TITLE
Calling Mitochondrial variants in the loading pipeline

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#116]
Calling mitochondrial variants as part of the seqr loading process will be beneficial for our collaborators.

## Background

Currently our loading pipeline only calls SNPs and Indels using Haplotype Caller. It would be of increased value to use a mitochondrial variant caller, and include these variants during the load.

To me, it looks like Broad use Mutect2, as discussed [here](). Code for a WDL pipeline lives under the gatk repository: https://github.com/broadinstitute/gatk/tree/master/scripts/mitochondria_m2_wdl

## Task list

- [ ] Investigate the suitability of the Broad Mitochondrial pipeline, including if there are any differences with DRAGEN aligned crams.
- [ ] Investigate if the MT pipeline requires any additional processing during loading.
- [ ] Determine whether to translate the workflow to Hail Batch, or keep as WDL
- [ ] Implement infrastructure around the MT pipeline
- [ ] Include these new MT variants during project load for seqr

## About this card

This is a FEATURE card and exists on the [Seqr project board](https://github.com/orgs/populationgenomics/projects/9). It's an amalgamation of the individual tasks from individual teams required to completely ship this feature. Having this card here makes it easier to track high-level progress on an issue.

I've listed a few tasks that have / will be needed to address to solve this enhancement. If you have related cards, please edit _this description_ to include tasks for those items. So hopefully, when this checklist is complete, we're able to say to collaborators we can generate and load structural variants.

Tagging @vladsaveliev, @vivbak as the card is particularly relevant to you when it is created.
