### ISSUE TITLE
Seqr loading wizard

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#117]
Onboarding collaborators is made difficult by the number of metadata templates they must fill out, and more difficult by the disconnect between providing their metadata templates, and us processing them.

## Background

Some onboarding wizard where collaborators directly provide their metadata too will be strongly beneficial, as it will provide:

- Immediate feedback about the quality of their metadata
- Less time required to collect, organise and process a collaborator's metadata, as currently it has been provided by email, uploaded to the bucket, slack, google drive (potentially all of the above for the same project).

Noting a few specific points:

- The person who collects the metadata, is rarely the same person who is uploading the data
- This process won't be applicable for all collaborators, some will interact directly with the SM server

## Task list

- [x] Structure metadata templates that give us all required information
- [ ] Design a user interface that allows collaborators to upload their own data with basic error checking (https://github.com/populationgenomics/seqr/pull/101)
- [ ] Synchronise metadata from this interface to the sample-metadata server
- [ ] [sort of related] Synchronise metadata from sample-metadata server back to seqr. This might relate to #115.

## About this card

This is a FEATURE card and exists on the [Seqr project board](https://github.com/orgs/populationgenomics/projects/9). It's an amalgamation of the individual tasks from individual teams required to completely ship this feature. Having this card here makes it easier to track high-level progress on an issue.

I've listed a few tasks that have / will be needed to address to solve this enhancement. If you have related cards, please edit _this description_ to include tasks for those items. So hopefully, when this checklist is complete, we're able to say to collaborators we can generate and load structural variants.

Tagging @daniaki, @violetbrina.
