### ISSUE TITLE
seqr-staging: Summary Data API 'update_external_analysis' 404

### ISSUE THREAD

**Issue by EddieLF** [populationgenomics/seqr#201]
**Describe the bug**
Since the upstream pull into the staging branch we now have the means to upload AIP reports to seqr. The 'summary_data/update_external_analysis' endpoint can be accessed by users in the `analysts` group to upload AIP results. The results are in JSON format and must contain individuals and variants that exist in the seqr projects & elastic indexes if connected. 

Once uploaded, upon submission an error is returned.
`VariantTagType matching query does not exist.`

The response is 404 and suggests the endpoint does not exist. The [API endpoint exists in `urls.py`](https://github.com/populationgenomics/seqr/blob/staging/seqr/urls.py#L338), and the function the endpoint calls is [`bulk_update_family_external_analysis`](https://github.com/populationgenomics/seqr/blob/staging/seqr/views/apis/summary_data_api.py#L145). Unfortunately, not much else is returned in the browser console log nor the cloud VM logs. The function makes several nested calls within the [`_load_aip_data`](https://github.com/populationgenomics/seqr/blob/staging/seqr/views/apis/summary_data_api.py#L185) function, including several using the `VariantTagType` model. It's unclear exactly where the 404 is coming from, but it likely relates to this model. It could suggest that migrations have not been run properly although after ssh'ing into the VM, all migrations have successfully ran. 

One other note is that the test for this function ([`test_bulk_update_family_external_analysis`](https://github.com/populationgenomics/seqr/blob/staging/seqr/views/apis/summary_data_api_tests.py#L431)) are commented out. The test is found in the `SummaryDataAPITests` module which inherits from `AirtableTest`, a currently unsupported testing framework within our forked seqr deployment. 

**Link to page(s) where bug is occurring**
- https://seqr-staging.populationgenomics.org.au/summary_data/external_analysis

**Scope of the bug**
The summary data API is not specific to a single project. 

**TODO**

- [ ] Try redeploying seqr-staging and re-running migrations

If that fails:
- [x] Run a local seqr instance
- [x] Connect to the prod elastic backend
- [x] Create a mock project and individuals / families that correspond to the index and AIP data
- [x] Attempt to upload an AIP report to the summary data API endpoint
- [x] Use breakpoints to debug the problematic code

**Screenshots**
![image](https://github.com/populationgenomics/seqr/assets/34049565/39ed5510-0958-44a2-af75-84ea80d3ee09)
```
{
    "timestamp": "2024-02-20 22:59:31,091",
    "severity": "WARNING",
    "httpRequest":
    {
        "requestMethod": "POST",
        "requestUrl": "http://seqr-staging.populationgenomics.org.au/api/summary_data/update_external_analysis",
        "status": 404,
        "responseSize": 64,
        "referer": "https://seqr-staging.populationgenomics.org.au/summary_data/external_analysis",
        "protocol": "HTTP/1.1"
    },
    "requestBody":
    {
        "dataType": "AIP",
        "familiesFile":
        {
            "uploaderState":
            {
                "items":
                [
                    {
                        "file":
                        {},
                        "index": 0,
                        "progress": 100,
                        "cancelled": false
                    }
                ],
                "info":
                [
                    "Parsed json from seqr_in.json"
                ],
                "uploadedFileId": "accf1d9e8de17b5f89b468c9fa8400a8"
            }
        },
        "message": "VariantTagType matching query does not exist.",
        "user": "edward.formaini@populationgenomics.org.au"
    }
}
```

```
{
    "timestamp": "2024-02-20 22:59:31,092",
    "severity": "WARNING",
    "message": "Not Found: /api/summary_data/update_external_analysis"
}
```

**Comment by EddieLF** [comment]
Closing this issue as the bug has been resolved.

In the fixtures, a [`new_variant_tag_types.json`](https://github.com/populationgenomics/seqr/blob/staging/seqr/fixtures/new_variant_tag_types.json) file containing a single AIP variant tag type needed to be loaded with the management command: `python manage.py loaddata new_variant_tag_types`.

Once this was loaded, I was able to import AIP variants through the endpoint. There was a little extra trouble with some variants in the `"support_vars"` field of the AIP report not existing in the family saved variants or the index variants, however once these were removed, the AIP report was successfully loaded.
