### ISSUE TITLE
Add GCP federated identity to Github deploy action

### ISSUE THREAD

**Issue by EddieLF** [populationgenomics/seqr#210]
**TODO**

https://github.com/populationgenomics/seqr/blob/main/.github/workflows/deploy.yaml#L23

- [ ] Generate federated identity credentials
- [ ] Insert `google-github-actions/auth@v2` action that uses the federated identity to Auth
- [ ] Update `google-github-actions/setup-gcloud` action version to latest

**Comment by EddieLF** [comment]
Resolved by https://github.com/populationgenomics/seqr/pull/214
